### ISSUE TITLE
Error when downloading the high-res data

### ISSUE THREAD

**Issue by CalibrationMe** [aditya-grover/climate-learn#116]
Hello, I got the following error when I try to download the 2.8125 res data of geopotential_500 with the following code:

```
cl.data.download_weatherbench(
    f"{root_directory}/geopotential",
    dataset="era5",
    variable="geopotential_500",
    resolution=2.8125 
)

```

The error message is that: 

```
climate_learn/data/download.py:85, in download_weatherbench(dst, dataset, variable, resolution)
     83         file.write(chunk)
     84 if ext == ".zip":
---> 85     with ZipFile(local_fn) as myzip:
     86         myzip.extractall(dst)
     87     os.unlink(local_fn)

BadZipFile: File is not a zip file

```

Could you help me to figure out the problem? Thanks!

**Comment by jasonjewik** [comment]
You are seeing this error because the data source for ERA5 WeatherBench data is unavailable. Currently, when I visit https://dataserv.ub.tum.de/, I get a 503 error.
```text
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.56 (Debian) Server at dataserv.ub.tum.de Port 443
```
This is beyond the ClimateLearn team's ability to control. However, when the data source comes back online, if you are still experiencing issues, please let us know.
