### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Skerre** [aditya-grover/climate-learn#31]
Dear climate-learn Team!
I tried to install you repository but both methods described in your readme file failed unfortunately.

The first output looks like this:

![image](https://user-images.githubusercontent.com/38685413/212553969-774f51c9-523e-4194-9875-25e9b977f103.png)

The second was a bit weirder, after I downloaded your code base and tried to install with the requirements file:

![image](https://user-images.githubusercontent.com/38685413/212554050-bdd9bfd5-3bae-4c79-a7b9-44d21acf69e0.png)

Do you have any ideas what I could do?

**Comment by jasonjewik** [comment]
Hi Skerre, thanks for flagging this issue, and thank you for including screenshots to reproduce the error. It seems like you're trying to install our package on a Windows computer. At the moment, our team can only guarantee the package will install correctly on Linux distros. (Platform-specific installation methods are on our roadmap for future features of ClimateLearn.) In the meantime, you can try the running the quickstart [Google Colab](https://colab.research.google.com/drive/1WiNEK1BHsiGzo_bT9Fcm8lea2H_ghNfa). Otherwise, if you need to use our package on your local machine, try installing on a Linux-based OS such as Ubuntu. If such a machine is not available to you, we recommend installing Windows Subsystem for Linux (WSL). See this link for installation instructions: https://learn.microsoft.com/en-us/windows/wsl/install. Please let us know if you have further troubles with installing our package by replying to this issue thread. Thanks!

**Comment by Skerre** [comment]
@jasonjewik Thank you for your help. I can move to a Linux machine (or use WSL indeed). Until then, good luck with the development!

Best,
Martin
