### ISSUE TITLE
Repetition in set_denormalization function

### ISSUE THREAD

**Issue by prakhar6sharma** [aditya-grover/climate-learn#48]
[`set_denormalization`](https://github.com/aditya-grover/climate-learn/blob/42915777b9f53475e7dfc6d463803e1f48c0e986/src/climate_learn/models/modules/forecast.py#L76) function in `climate_learn.models.modules.forecast.py` has repetition of lines.

Particularly this piece of code is repeated thrice.
`mean_mean_denorm, mean_std_denorm = -mean / std, 1 / std`
`self.mean_denormalize = transforms.Normalize(mean_mean_denorm, mean_std_denorm)`

`std_mean_denorm, std_std_denorm = np.zeros_like(std), 1 / std`
`self.std_denormalize = transforms.Normalize(std_mean_denorm, std_std_denorm)`

**Comment by prakhar6sharma** [comment]
I will submit the PR for this one.

**Comment by tung-nd** [comment]
This is actually a feature not a bug 😄 I think it has to do with the parametric models where we predict the mean and variance of a Gaussian distribution, instead of just outputting a mean prediction. These seemingly redundant lines therefore are used to set the denormalization for both the mean and the variance.
@bulaienTang can have more inputs here

**Comment by bulaienTang** [comment]
Ohh, yes these mean & variance denormalization are different methods, but I think there are actually redundant lines for some reason 😨

I think this is what Prakhar meant.
<img width="569" alt="Screenshot 2023-02-08 at 12 04 42 AM" src="https://user-images.githubusercontent.com/34512891/217470972-203025e8-87a6-4d83-a3cd-6b75b838e880.png">

**Comment by bulaienTang** [comment]
Yeah, I checked the commit history, it should be due to duplication made when merging the uncertainty repo into the climatelearn
